server:
  port: 6006

spring:
  application:
    name: eden_web
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/linkknown_eden_web?serverTimezone=UTC
    username: root
    password: root

